name: PMD Code Scanning

on:
  push:

jobs:
  pmd-code-scan:
    permissions:
      contents: read
      security-events: write
      actions: read

    name: Run code scanning
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4

      - name: Set up java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Run PMD
        id: pmd
        uses: pmd/pmd-github-action@967a81f8b657c87f7c3e96b62301cb1a48efef29
        continue-on-error: true
        with:
          version: "7.0.0"
          sourcePath: "src/main/java"
          rulesets: "rulesets/java/quickstart.xml"
          analyzeModifiedFilesOnly: false

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif

      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations != 0
        run: exit 1