name: PMD Code Scanning

on:
  push:

jobs:
  pmd:
    name: Run code scanning
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4

      - name: Set up java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Run PMD
        uses: pmd/pmd-github-action@v2
        id: pmd
        with:
          version: "7.0.0-rc4"
          sourcePath: "src/main/java"
          rulesets: "rulesets/java/quickstart.xml,ruleset.xml"

      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations != 0
        run: exit 1

      - name: Make report file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif